[package]
name = "jljoin"
version = "0.1.0"
authors = ["winebarrel <sugawara@winebarrel.jp>"]
edition = "2018"

[dependencies]
getopts = "0.2"
serde_json = "1.0"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"
indoc = "1.0"
